language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HDXSX5c6RZ3UxLIzKQf08obzA9Kt2UD6oiR6oDwc3GRVCeyEmqUSoRsRFqmxH5iRHtma9v7Ps/4Kv6s/5hMOxxcboz0nffhCc0UOpkqN2vZlOvSEGQITxvckQ6v3PFGhWilPAfhLn39qm8SAdDMKCPKc31/XONuV79o77MOkHtrABW71tluhJspPLxqVFW5Ddv/nEH4aIO7EbwTzdXQxzRSQhCIcCsNy76IGxxEEVj3kUcWiIX7PbviErjWGwW7tKFbQ4fLRnhFeZxmZzm2f/SJ+bLUhsYFUGILq4jW5dP6lligV28sfAL11tUaqaFHW61TaXHyg/MYgOcSJQqlkqvPebFV710vAePuZIbBSwMjtqZuceyKr0q5M563sEPtqkFeGzJvWN89qjnHB1zcBNNdCacNzhfwqjoEo+tdTrX04jYe//AF0iIHawJLbAZcCi4pm4+Go3luh5ST4UsIX3rtdx2C3idQX/4En/PVV1Xa8YEoQBTUvlm9LdOK/T6VqY+hsLSmujLUwxFO34HPpojVkUfRaTpb9FyNlAoO2Fz+HY9t/qDy9P/NzGu8lrcfsioTPLkNGlBn/kvtLxteziBVDLtr9hpl/dATZ+6/2kDZHeKkpZmedJZLSkA0RZIVe/nWP7Uo3VigXaQ9cntSmbk0sPO6kqEt+OjBQny5+aSs=
  file:
    - "normalize-uri.js"
    - "normalize-uri.min.js"
  on:
    tags: true
