language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: klNBtEJJJLyWZsezF3ey6NsckH9DbpCLITL0sRbKHpcnjYbnWh8zQahGtbmfjCFfCGuqu6BB1AEEyw/rKYplRzBWXkPTYBKwpfYA4H2YTaMlkhI3og6Lpfh1KIw5HaAJLPSXpJN6bJv9qsi9KUlhs5bBinw9rxJrMDIBWhFSt2fa3XhEZUkuGKAg7+wjZX1s6SEMdxZCeADQwx9+xROzrnR0km3cq8yvnJqcM9rfT/nYC7E/FTwOLUoSKfQybtOSX6I/qSe4cf5+K7MqBEw2gafz4z7IkUpTMuWk8tBuwA5x1/iTzmW8aYCHnmY+9pChIHT8oSvvPP3XTdPCT+7hUAOBssFlbHXfRVtw4NOprW1gYKlI3hs0UVUptDq0KfGY94v+He6nN/oSlGgUc1A9C4B7e7LEY6V6JRwKzpH8YtXB/5TnCShsIvTQazxxbnIz0dVSrxaoB9SDkHICALASUtkwg65qE+QBV5dXYAIMJUVQxwFmUX1G/FCoGSxsVxT4shQBF3LyEqhfifu4O35EuDgtsOpfGcvjHjg7yiy56iO1nUbwKqjQyMuPp2vybJIotXTVoTgv1XZW9dPXIc1mRN3vK9E1FyJuQJF0WuyHst3e+mkW4A3Q7XHXB77Ax0wLWpLSGRT3CnY02wPgJDfIAfrGYPNbzyynYG5bia0ZYC0=
  file:
    - 'normalize-uri.js'
    - 'normalize-uri.min.js'
  on:
    tags: true
